### ISSUE TITLE
PermissionError when selecting points

### ISSUE THREAD

**Issue by nilseling** [BodenmillerGroup/napari-imcreg#11]
This error occurs sometimes randomly when assigning points:

```
ERROR:root:Unhandled exception:
Traceback (most recent call last):
  File "/Users/immucan/opt/anaconda3/envs/napping/lib/python3.9/site-packages/vispy/app/backends/_qt.py", line 453, in mouseReleaseEvent
    self._vispy_mouse_release(
  File "/Users/immucan/opt/anaconda3/envs/napping/lib/python3.9/site-packages/vispy/app/base.py", line 221, in _vispy_mouse_release
    ev = self._vispy_canvas.events.mouse_release(**kwargs)
  File "/Users/immucan/opt/anaconda3/envs/napping/lib/python3.9/site-packages/vispy/util/event.py", line 455, in __call__
    self._invoke_callback(cb, event)
  File "/Users/immucan/opt/anaconda3/envs/napping/lib/python3.9/site-packages/vispy/util/event.py", line 473, in _invoke_callback
    _handle_exception(self.ignore_callback_errors,
  File "/Users/immucan/opt/anaconda3/envs/napping/lib/python3.9/site-packages/vispy/util/event.py", line 471, in _invoke_callback
    cb(event)
  File "/Users/immucan/opt/anaconda3/envs/napping/lib/python3.9/site-packages/napari/_qt/qt_viewer.py", line 709, in on_mouse_release
    mouse_release_callbacks(layer, event)
  File "/Users/immucan/opt/anaconda3/envs/napping/lib/python3.9/site-packages/napari/utils/interactions.py", line 188, in mouse_release_callbacks
    next(gen)
  File "/Users/immucan/opt/anaconda3/envs/napping/lib/python3.9/site-packages/napari/layers/points/_points_mouse_bindings.py", line 99, in add
    layer.add(layer.coordinates)
  File "/Users/immucan/opt/anaconda3/envs/napping/lib/python3.9/site-packages/napari/layers/points/points.py", line 1687, in add
    self.data = np.append(self.data, np.atleast_2d(coord), axis=0)
  File "/Users/immucan/opt/anaconda3/envs/napping/lib/python3.9/site-packages/napari/layers/points/points.py", line 527, in data
    self.selected_data = set(np.arange(cur_npoints, len(data)))
  File "/Users/immucan/opt/anaconda3/envs/napping/lib/python3.9/site-packages/napari/layers/points/points.py", line 1295, in selected_data
    self.current_properties = properties
  File "/Users/immucan/opt/anaconda3/envs/napping/lib/python3.9/site-packages/napari/layers/points/points.py", line 657, in current_properties
    self.events.current_properties()
  File "/Users/immucan/opt/anaconda3/envs/napping/lib/python3.9/site-packages/napari/utils/events/event.py", line 510, in __call__
    self._invoke_callback(cb, event)
  File "/Users/immucan/opt/anaconda3/envs/napping/lib/python3.9/site-packages/napari/utils/events/event.py", line 527, in _invoke_callback
    _handle_exception(
  File "/Users/immucan/opt/anaconda3/envs/napping/lib/python3.9/site-packages/napari/utils/events/event.py", line 525, in _invoke_callback
    cb(event)
  File "/Users/immucan/opt/anaconda3/envs/napping/lib/python3.9/site-packages/napping/napping.py", line 588, in on_points_layer_current_properties_changed
    self._controller._handle_control_points_changed()
  File "/Users/immucan/opt/anaconda3/envs/napping/lib/python3.9/site-packages/napping/napping.py", line 440, in _handle_control_points_changed
    self._current_transformed_coords.to_csv(self.current_transformed_coords_dest_file_path, index=False)
  File "/Users/immucan/opt/anaconda3/envs/napping/lib/python3.9/site-packages/pandas/core/generic.py", line 3386, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "/Users/immucan/opt/anaconda3/envs/napping/lib/python3.9/site-packages/pandas/io/formats/format.py", line 1083, in to_csv
    csv_formatter.save()
  File "/Users/immucan/opt/anaconda3/envs/napping/lib/python3.9/site-packages/pandas/io/formats/csvs.py", line 228, in save
    with get_handle(
  File "/Users/immucan/opt/anaconda3/envs/napping/lib/python3.9/site-packages/pandas/io/common.py", line 642, in get_handle
    handle = open(
PermissionError: [Errno 13] Permission denied: '/Volumes/immucan_volume/raw_data/Panel_1/Batch20201113/IF_regions/csv_coordinates_transformed/XYZ.csv'
```

I understand it's problematic working directly on a mounted volume but maybe there is a way to safeguard against this error?
Cheers,

Nils

**Comment by jwindhager** [comment]
Is this reproducible?

In particular, does it maybe happen when you select two control points with almost no delay in between? I could imagine that the OS/Python in such cases don't release the file handle fast enough, and therefore napping is trying to write a file that is still open from a previous write operation. 

Otherwise, it'll be tricky to pinpoint the exact source of the error. Any suggestions how napping should behave in such situations?

**Comment by nilseling** [comment]
It's hard to tell. It doesn't depend on how fast I click. And when closing/opening the GUI the error is only sometimes resolved. I'll continue observing this and try to figure out when specifically it occurs.

**Comment by jwindhager** [comment]
Please reopen this issue if the problem persists after upgrading to v0.1.5
