### ISSUE TITLE
Cannot change data-type for object array.

### ISSUE THREAD

**Issue by nilseling** [BodenmillerGroup/napari-imcreg#16]
Hey,

I'm not so sure where this issue is coming from, so I'm posting it here.

```
ERROR:root:Unhandled exception:
Traceback (most recent call last):
  File "/Users/immucan/opt/anaconda3/envs/napping/lib/python3.9/site-packages/numpy/lib/arraysetops.py", line 284, in unique
    consolidated = ar.view(dtype)
  File "/Users/immucan/opt/anaconda3/envs/napping/lib/python3.9/site-packages/numpy/core/_internal.py", line 459, in _view_is_safe
    raise TypeError("Cannot change data-type for object array.")
TypeError: Cannot change data-type for object array.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/immucan/opt/anaconda3/envs/napping/lib/python3.9/site-packages/vispy/app/backends/_qt.py", line 453, in mouseReleaseEvent
    self._vispy_mouse_release(
  File "/Users/immucan/opt/anaconda3/envs/napping/lib/python3.9/site-packages/vispy/app/base.py", line 221, in _vispy_mouse_release
    ev = self._vispy_canvas.events.mouse_release(**kwargs)
  File "/Users/immucan/opt/anaconda3/envs/napping/lib/python3.9/site-packages/vispy/util/event.py", line 455, in __call__
    self._invoke_callback(cb, event)
  File "/Users/immucan/opt/anaconda3/envs/napping/lib/python3.9/site-packages/vispy/util/event.py", line 473, in _invoke_callback
    _handle_exception(self.ignore_callback_errors,
  File "/Users/immucan/opt/anaconda3/envs/napping/lib/python3.9/site-packages/vispy/util/event.py", line 471, in _invoke_callback
    cb(event)
  File "/Users/immucan/opt/anaconda3/envs/napping/lib/python3.9/site-packages/napari/_qt/qt_viewer.py", line 714, in on_mouse_release
    mouse_release_callbacks(layer, event)
  File "/Users/immucan/opt/anaconda3/envs/napping/lib/python3.9/site-packages/napari/utils/interactions.py", line 188, in mouse_release_callbacks
    next(gen)
  File "/Users/immucan/opt/anaconda3/envs/napping/lib/python3.9/site-packages/napari/layers/points/_points_mouse_bindings.py", line 99, in add
    layer.add(layer.coordinates)
  File "/Users/immucan/opt/anaconda3/envs/napping/lib/python3.9/site-packages/napari/layers/points/points.py", line 1687, in add
    self.data = np.append(self.data, np.atleast_2d(coord), axis=0)
  File "/Users/immucan/opt/anaconda3/envs/napping/lib/python3.9/site-packages/napari/layers/points/points.py", line 527, in data
    self.selected_data = set(np.arange(cur_npoints, len(data)))
  File "/Users/immucan/opt/anaconda3/envs/napping/lib/python3.9/site-packages/napari/layers/points/points.py", line 1289, in selected_data
    properties = {
  File "/Users/immucan/opt/anaconda3/envs/napping/lib/python3.9/site-packages/napari/layers/points/points.py", line 1290, in <dictcomp>
    k: np.unique(v[index], axis=0) for k, v in self.properties.items()
  File "<__array_function__ internals>", line 5, in unique
  File "/Users/immucan/opt/anaconda3/envs/napping/lib/python3.9/site-packages/numpy/lib/arraysetops.py", line 295, in unique
    raise TypeError(msg.format(dt=ar.dtype)) from e
TypeError: The axis argument to unique is not supported for dtype object
```

Thaaaaaaank you!

**Comment by nilseling** [comment]
This issue was caused by an empty control points file that only contains the header row. When deleting the file it works again. @jwindhager please close this issue if you're happy with this behaviour.
