### ISSUE TITLE
Weird bug when selecting points

### ISSUE THREAD

**Issue by nilseling** [BodenmillerGroup/napari-imcreg#17]
Hey @jwindhager 

we're having this new bug: when selecting points on the images, an outline of the cross appears but the cursor is locked to the image until rapid (maybe double) clicking. Again, it's a bit hard to describe the GUI.
Here is the error message that I didn't understand:

```
ERROR:root:Unhandled exception:
Traceback (most recent call last):
  File "/Users/immucan/opt/anaconda3/envs/napping/lib/python3.9/site-packages/numpy/lib/arraysetops.py", line 284, in unique
    consolidated = ar.view(dtype)
  File "/Users/immucan/opt/anaconda3/envs/napping/lib/python3.9/site-packages/numpy/core/_internal.py", line 459, in _view_is_safe
    raise TypeError("Cannot change data-type for object array.")
TypeError: Cannot change data-type for object array.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/immucan/opt/anaconda3/envs/napping/lib/python3.9/site-packages/vispy/app/backends/_qt.py", line 453, in mouseReleaseEvent
    self._vispy_mouse_release(
  File "/Users/immucan/opt/anaconda3/envs/napping/lib/python3.9/site-packages/vispy/app/base.py", line 221, in _vispy_mouse_release
    ev = self._vispy_canvas.events.mouse_release(**kwargs)
  File "/Users/immucan/opt/anaconda3/envs/napping/lib/python3.9/site-packages/vispy/util/event.py", line 455, in __call__
    self._invoke_callback(cb, event)
  File "/Users/immucan/opt/anaconda3/envs/napping/lib/python3.9/site-packages/vispy/util/event.py", line 473, in _invoke_callback
    _handle_exception(self.ignore_callback_errors,
  File "/Users/immucan/opt/anaconda3/envs/napping/lib/python3.9/site-packages/vispy/util/event.py", line 471, in _invoke_callback
    cb(event)
  File "/Users/immucan/opt/anaconda3/envs/napping/lib/python3.9/site-packages/napari/_qt/qt_viewer.py", line 714, in on_mouse_release
    mouse_release_callbacks(layer, event)
  File "/Users/immucan/opt/anaconda3/envs/napping/lib/python3.9/site-packages/napari/utils/interactions.py", line 188, in mouse_release_callbacks
    next(gen)
  File "/Users/immucan/opt/anaconda3/envs/napping/lib/python3.9/site-packages/napari/layers/points/_points_mouse_bindings.py", line 99, in add
    layer.add(layer.coordinates)
  File "/Users/immucan/opt/anaconda3/envs/napping/lib/python3.9/site-packages/napari/layers/points/points.py", line 1687, in add
    self.data = np.append(self.data, np.atleast_2d(coord), axis=0)
  File "/Users/immucan/opt/anaconda3/envs/napping/lib/python3.9/site-packages/napari/layers/points/points.py", line 527, in data
    self.selected_data = set(np.arange(cur_npoints, len(data)))
  File "/Users/immucan/opt/anaconda3/envs/napping/lib/python3.9/site-packages/napari/layers/points/points.py", line 1289, in selected_data
    properties = {
  File "/Users/immucan/opt/anaconda3/envs/napping/lib/python3.9/site-packages/napari/layers/points/points.py", line 1290, in <dictcomp>
    k: np.unique(v[index], axis=0) for k, v in self.properties.items()
  File "<__array_function__ internals>", line 5, in unique
  File "/Users/immucan/opt/anaconda3/envs/napping/lib/python3.9/site-packages/numpy/lib/arraysetops.py", line 295, in unique
    raise TypeError(msg.format(dt=ar.dtype)) from e
TypeError: The axis argument to unique is not supported for dtype object
```

**Comment by jwindhager** [comment]
Would you be able to provide information regarding your environment (version numbers of napping, napari, napari-imc, napari-czifile2 in particular, where applicable)?

**Comment by nilseling** [comment]
Ah yes, of course:

```
# Name                    Version                   Build  Channel
alabaster                 0.7.12                   pypi_0    pypi
appdirs                   1.4.4                    pypi_0    pypi
appnope                   0.1.2                    pypi_0    pypi
babel                     2.9.0                    pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
ca-certificates           2021.1.19            hecd8cb5_0  
cachey                    0.2.1                    pypi_0    pypi
certifi                   2020.12.5        py39hecd8cb5_0  
chardet                   4.0.0                    pypi_0    pypi
cycler                    0.10.0                   pypi_0    pypi
czifile                   2019.7.2                 pypi_0    pypi
dask                      2021.2.0                 pypi_0    pypi
decorator                 4.4.2                    pypi_0    pypi
docstring-parser          0.7.3                    pypi_0    pypi
docutils                  0.16                     pypi_0    pypi
freetype-py               2.2.0                    pypi_0    pypi
heapdict                  1.0.1                    pypi_0    pypi
idna                      2.10                     pypi_0    pypi
imagecodecs               2020.12.24               pypi_0    pypi
imageio                   2.9.0                    pypi_0    pypi
imagesize                 1.2.0                    pypi_0    pypi
imctools                  2.1.4                    pypi_0    pypi
ipykernel                 5.4.3                    pypi_0    pypi
ipython                   7.20.0                   pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
jedi                      0.18.0                   pypi_0    pypi
jinja2                    2.11.3                   pypi_0    pypi
jupyter-client            6.1.11                   pypi_0    pypi
jupyter-core              4.7.1                    pypi_0    pypi
kiwisolver                1.3.1                    pypi_0    pypi
libcxx                    10.0.0                        1  
libedit                   3.1.20191231         h1de35cc_1  
libffi                    3.3                  hb1e8313_2  
magicgui                  0.2.6                    pypi_0    pypi
markupsafe                1.1.1                    pypi_0    pypi
matplotlib                3.3.4                    pypi_0    pypi
napari                    0.4.5                    pypi_0    pypi
napari-console            0.0.3                    pypi_0    pypi
napari-czifile2           0.1.2.dev1+g4103de7          pypi_0    pypi
napari-imc                0.4.5                    pypi_0    pypi
napari-plugin-engine      0.1.9                    pypi_0    pypi
napari-svg                0.1.4                    pypi_0    pypi
napping                   0.1.6                    pypi_0    pypi
ncurses                   6.2                  h0a44026_1  
networkx                  2.5                      pypi_0    pypi
numpy                     1.20.1                   pypi_0    pypi
numpydoc                  1.1.0                    pypi_0    pypi
openssl                   1.1.1i               h9ed2024_0  
packaging                 20.9                     pypi_0    pypi
pandas                    1.2.2                    pypi_0    pypi
parso                     0.8.1                    pypi_0    pypi
pexpect                   4.8.0                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    8.1.0                    pypi_0    pypi
pip                       20.3.3           py39hecd8cb5_0  
prompt-toolkit            3.0.14                   pypi_0    pypi
psutil                    5.8.0                    pypi_0    pypi
ptyprocess                0.7.0                    pypi_0    pypi
pydantic                  1.7.3                    pypi_0    pypi
pygments                  2.7.4                    pypi_0    pypi
pyopengl                  3.1.5                    pypi_0    pypi
pyparsing                 2.4.7                    pypi_0    pypi
pyqt5                     5.15.2                   pypi_0    pypi
pyqt5-sip                 12.8.1                   pypi_0    pypi
python                    3.9.1                h88f2d9e_2  
python-dateutil           2.8.1                    pypi_0    pypi
pytz                      2021.1                   pypi_0    pypi
pywavelets                1.1.1                    pypi_0    pypi
pyyaml                    5.4.1                    pypi_0    pypi
pyzmq                     22.0.2                   pypi_0    pypi
qtconsole                 5.0.2                    pypi_0    pypi
qtpy                      1.9.0                    pypi_0    pypi
readline                  8.1                  h9ed2024_0  
requests                  2.25.1                   pypi_0    pypi
scikit-image              0.18.1                   pypi_0    pypi
scipy                     1.6.0                    pypi_0    pypi
setuptools                52.0.0           py39hecd8cb5_0  
six                       1.15.0                   pypi_0    pypi
snowballstemmer           2.1.0                    pypi_0    pypi
sphinx                    3.4.3                    pypi_0    pypi
sphinxcontrib-applehelp   1.0.2                    pypi_0    pypi
sphinxcontrib-devhelp     1.0.2                    pypi_0    pypi
sphinxcontrib-htmlhelp    1.0.3                    pypi_0    pypi
sphinxcontrib-jsmath      1.0.1                    pypi_0    pypi
sphinxcontrib-qthelp      1.0.3                    pypi_0    pypi
sphinxcontrib-serializinghtml 1.1.4                    pypi_0    pypi
sqlite                    3.33.0               hffcf06c_0  
tifffile                  2021.2.1                 pypi_0    pypi
tk                        8.6.10               hb0a8c7a_0  
toolz                     0.11.1                   pypi_0    pypi
tornado                   6.1                      pypi_0    pypi
traitlets                 5.0.5                    pypi_0    pypi
typing-extensions         3.7.4.3                  pypi_0    pypi
tzdata                    2020f                h52ac0ba_0  
urllib3                   1.26.3                   pypi_0    pypi
vispy                     0.6.6                    pypi_0    pypi
wcwidth                   0.2.5                    pypi_0    pypi
wheel                     0.36.2             pyhd3eb1b0_0  
wrapt                     1.12.1                   pypi_0    pypi
xmltodict                 0.12.0                   pypi_0    pypi
xtiff                     0.6.4                    pypi_0    pypi
xz                        5.2.5                h1de35cc_0  
zlib                      1.2.11               h1de35cc_3  
```

**Comment by jwindhager** [comment]
Not reproducible for current version (0.1.7) of napping. Potentially related to outdated version (0.1.6, see above), therefore closing this issue. Please reopen if problem persists.
