### ISSUE TITLE
Switching images via the "left" and "right" buttons don't seem to work

### ISSUE THREAD

**Issue by nilseling** [BodenmillerGroup/napari-imcreg#8]
When specifying multiple files via directories it's fine to load the first set of images (mcd and chi) and assign the control points.
Once when I want to switch to the next set of files via the "right arrow" button, I get this error:

```
ERROR:root:Unhandled exception:
Traceback (most recent call last):
  File "/Users/immucan/opt/anaconda3/envs/napping/lib/python3.9/site-packages/napping/widgets/napping_widget.py", line 37, in on_next_button_clicked
    view_controller.controller.show_next()
  File "/Users/immucan/opt/anaconda3/envs/napping/lib/python3.9/site-packages/napping/napping.py", line 165, in show_next
    return self._show()
  File "/Users/immucan/opt/anaconda3/envs/napping/lib/python3.9/site-packages/napping/napping.py", line 413, in _show
    self._target_view_controller.show(self.current_target_image_file_path)
  File "/Users/immucan/opt/anaconda3/envs/napping/lib/python3.9/site-packages/napping/napping.py", line 507, in show
    self._close_image()
  File "/Users/immucan/opt/anaconda3/envs/napping/lib/python3.9/site-packages/napping/napping.py", line 569, in _close_image
    while len(self._image_layers) > 0:
TypeError: object of type 'NoneType' has no len()

ERROR:root:Unhandled exception:
Traceback (most recent call last):
  File "/Users/immucan/opt/anaconda3/envs/napping/lib/python3.9/site-packages/vispy/app/backends/_qt.py", line 453, in mouseReleaseEvent
    self._vispy_mouse_release(
  File "/Users/immucan/opt/anaconda3/envs/napping/lib/python3.9/site-packages/vispy/app/base.py", line 221, in _vispy_mouse_release
    ev = self._vispy_canvas.events.mouse_release(**kwargs)
  File "/Users/immucan/opt/anaconda3/envs/napping/lib/python3.9/site-packages/vispy/util/event.py", line 455, in __call__
    self._invoke_callback(cb, event)
  File "/Users/immucan/opt/anaconda3/envs/napping/lib/python3.9/site-packages/vispy/util/event.py", line 473, in _invoke_callback
    _handle_exception(self.ignore_callback_errors,
  File "/Users/immucan/opt/anaconda3/envs/napping/lib/python3.9/site-packages/vispy/util/event.py", line 471, in _invoke_callback
    cb(event)
  File "/Users/immucan/opt/anaconda3/envs/napping/lib/python3.9/site-packages/napari/_qt/qt_viewer.py", line 709, in on_mouse_release
    mouse_release_callbacks(layer, event)
  File "/Users/immucan/opt/anaconda3/envs/napping/lib/python3.9/site-packages/napari/utils/interactions.py", line 188, in mouse_release_callbacks
    next(gen)
  File "/Users/immucan/opt/anaconda3/envs/napping/lib/python3.9/site-packages/napari/layers/points/_points_mouse_bindings.py", line 99, in add
    layer.add(layer.coordinates)
  File "/Users/immucan/opt/anaconda3/envs/napping/lib/python3.9/site-packages/napari/layers/points/points.py", line 1687, in add
    self.data = np.append(self.data, np.atleast_2d(coord), axis=0)
  File "/Users/immucan/opt/anaconda3/envs/napping/lib/python3.9/site-packages/napari/layers/points/points.py", line 527, in data
    self.selected_data = set(np.arange(cur_npoints, len(data)))
  File "/Users/immucan/opt/anaconda3/envs/napping/lib/python3.9/site-packages/napari/layers/points/points.py", line 1295, in selected_data
    self.current_properties = properties
  File "/Users/immucan/opt/anaconda3/envs/napping/lib/python3.9/site-packages/napari/layers/points/points.py", line 657, in current_properties
    self.events.current_properties()
  File "/Users/immucan/opt/anaconda3/envs/napping/lib/python3.9/site-packages/napari/utils/events/event.py", line 510, in __call__
    self._invoke_callback(cb, event)
  File "/Users/immucan/opt/anaconda3/envs/napping/lib/python3.9/site-packages/napari/utils/events/event.py", line 527, in _invoke_callback
    _handle_exception(
  File "/Users/immucan/opt/anaconda3/envs/napping/lib/python3.9/site-packages/napari/utils/events/event.py", line 525, in _invoke_callback
    cb(event)
  File "/Users/immucan/opt/anaconda3/envs/napping/lib/python3.9/site-packages/napping/napping.py", line 585, in on_points_layer_current_properties_changed
    self._controller._handle_control_points_changed()
  File "/Users/immucan/opt/anaconda3/envs/napping/lib/python3.9/site-packages/napping/napping.py", line 438, in _handle_control_points_changed
    self.target_view_controller.refresh()
  File "/Users/immucan/opt/anaconda3/envs/napping/lib/python3.9/site-packages/napping/napping.py", line 513, in refresh
    self._widget.refresh()
  File "/Users/immucan/opt/anaconda3/envs/napping/lib/python3.9/site-packages/napping/widgets/napping_widget.py", line 51, in refresh
    path_name = self._view_controller.image_path.name
AttributeError: 'NoneType' object has no attribute 'name'
```

The next czi file loads but not the next mcd.
Cheers,

Nils

**Comment by jwindhager** [comment]
Oops, forgot that, when opening mcd files, no layers are added to the viewer - fixing asap
